version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=2505
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  
  tourist-be:
    depends_on:
      - mysql_db
    build: .
    container_name: tourist-be
    environment:
      - DATABASE_URL=mysql://root:2505@mysql_db:3306/tourist?schema=public
    ports:
      - 8080:8080
    networks:
      - node-network
    

volumes:
  mysql_db:
    driver: local
networks:
  node-network: